refresh_rate: 15 seconds

appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%d/%m/%Y- %T%.3f)} | {({l}):5.5} | [{M}] — {m}{n}"
    filters:
      - kind: threshold
        level: debug

root:
  level: trace
  appenders: 
    - stdout

loggers:
  binance:
    level: trace
    appenders:
      - stdout
    additive: false

  okex:
    level: trace
    appenders:
      - stdout
    additive: false

  sdk:
    level: trace
    appenders:
      - stdout
    additive: false
